title: Chroma9
description: Musician, Developer, Voice Actor, and Void Monster.
color: a0a0a0

youtube: https://youtube.com/@Chroma9
twitter: https://twitter.com/OfficialChroma9
twitch: https://www.twitch.tv/Chroma9Live
spotify: https://open.spotify.com/artist/4pKo6ILFbitfEhqLALoamR
bandcamp: https://chroma9.bandcamp.com/
github: https://github.com/Chroma9